### PR TITLE
Added documentation for builtin functions

### PR DESCRIPTION
**Pull request by m0nt3-q**
I wrote some documentation. I'm not set on the format, but in general it gets the job done.

### CODE REVIEW

**Comment by kgabis** [comment]
I've made some changes before merging. It will serve as a stub for future documentation, but having a list of builtins should be useful to users.
Mind if I ask if you're using Ape in a project and what's your experience with it?

**Comment by m0nt3-q** [comment]
Awesome, I look forward to keeping it up-to date and expanding it.

I'm using Ape in a new version of a game (Bit World Hero) I'm going to release soon. It's useful for reducing a lot of effort when it comes to handling high-level game logic and structures, like AI logic and map data, as opposed to doing the same in C.

I really like how you added relative/absolute path module loading in the last update, and I appreciate how easy it was to integrate!

I noticed there's no `str_to_map` function, and that would be tremendously useful, as I was hoping for a map-to-string-to-arraybuffer going from Ape to C to JavaScript ArrayBuffer to store data, and then doing the reverse for loading. (It's a little odd, but it's sharing game code with a node.js server and this reduces glue-code). I am not opposed to writing something like this myself, but I will need to make some time for it, to understand the best way to accomplish this.

**Comment by kgabis** [comment]
Cool, good to know that someone is using it in the wild :)
What do you mean by```str_to_map``` function?

**Comment by m0nt3-q** [comment]
A function that could convert a `string` into a `map`, similar to `JSON.parse()`

**Comment by kgabis** [comment]
I might integrate a json parser in future but it's not very high on the list of my priorities right now.

**Comment by m0nt3-q** [comment]
Not a problem! Looking forward to updates.

**Pull request merged**
